config/routes.rb
Rails.application.routes.draw do
  
  resources :transactions
  resources :user_infos
  resources :accounts
  resources :atm_machines
  devise_for :users
  root'atm_machines#index'

end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :set_user_info, only: [:show, :edit, :update, :destroy]

  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.all
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
  end

  # GET /user_infos/new
  def new
    @user_info = UserInfo.new
  end

  # GET /user_infos/1/edit
  def edit
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    @user_info = UserInfo.new(user_info_params)

    respond_to do |format|
      if @user_info.save
        format.html { redirect_to @user_info, notice: 'User info was successfully created.' }
        format.json { render :show, status: :created, location: @user_info }
      else
        format.html { render :new }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_infos/1
  # PATCH/PUT /user_infos/1.json
  def update
    respond_to do |format|
      if @user_info.update(user_info_params)
        format.html { redirect_to @user_info, notice: 'User info was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_info }
      else
        format.html { render :edit }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  def destroy
    @user_info.destroy
    respond_to do |format|
      format.html { redirect_to user_infos_url, notice: 'User info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_info
      @user_info = UserInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_info_params
      params.require(:user_info).permit(:first_name, :last_name, :email, :phone, :user_id, :user_id)
    end
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos/_form.html.erb
<%= form_for(@user_info) do |f| %>
  <% if @user_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>

      <ul>
      <% @user_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_infos/edit.html.erb
<h1>Editing User Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_info %> |
<%= link_to 'Back', user_infos_path %>

app/views/user_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Infos</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>User</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_infos.each do |user_info| %>
      <tr>
        <td><%= user_info.first_name %></td>
        <td><%= user_info.last_name %></td>
        <td><%= user_info.email %></td>
        <td><%= user_info.phone %></td>
        <td><%= user_info.user_id %></td>
        <td><%= user_info.user %></td>
        <td><%= link_to 'Show', user_info %></td>
        <td><%= link_to 'Edit', edit_user_info_path(user_info) %></td>
        <td><%= link_to 'Destroy', user_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User info', new_user_info_path %>

app/views/user_infos/new.html.erb
<h1>New User Info</h1>

<%= render 'form' %>

<%= link_to 'Back', user_infos_path %>

app/views/user_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user_info.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user_info.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_info.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user_info.phone %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_info.user_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_info.user %>
</p>

<%= link_to 'Edit', edit_user_info_path(@user_info) %> |
<%= link_to 'Back', user_infos_path %>