config/routes.rb
Rails.application.routes.draw do
  
  resources :transactions
  resources :user_infos
  resources :accounts
  resources :atm_machines
  devise_for :users
  root'atm_machines#index'

end

app/models/atm_machine.rb
class AtmMachine < ActiveRecord::Base
    geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/atm_machines_controller.rb
class AtmMachinesController < ApplicationController
  before_action :set_atm_machine, only: [:show, :edit, :update, :destroy]

  # GET /atm_machines
  # GET /atm_machines.json
  def index
    @atm_machines = AtmMachine.all
  end

  # GET /atm_machines/1
  # GET /atm_machines/1.json
  def show
  end

  # GET /atm_machines/new
  def new
    @atm_machine = AtmMachine.new
  end

  # GET /atm_machines/1/edit
  def edit
  end

  # POST /atm_machines
  # POST /atm_machines.json
  def create
    @atm_machine = AtmMachine.new(atm_machine_params)

    respond_to do |format|
      if @atm_machine.save
        format.html { redirect_to @atm_machine, notice: 'Atm machine was successfully created.' }
        format.json { render :show, status: :created, location: @atm_machine }
      else
        format.html { render :new }
        format.json { render json: @atm_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atm_machines/1
  # PATCH/PUT /atm_machines/1.json
  def update
    respond_to do |format|
      if @atm_machine.update(atm_machine_params)
        format.html { redirect_to @atm_machine, notice: 'Atm machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @atm_machine }
      else
        format.html { render :edit }
        format.json { render json: @atm_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atm_machines/1
  # DELETE /atm_machines/1.json
  def destroy
    @atm_machine.destroy
    respond_to do |format|
      format.html { redirect_to atm_machines_url, notice: 'Atm machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atm_machine
      @atm_machine = AtmMachine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atm_machine_params
      params.require(:atm_machine).permit(:address, :latitude, :longitude, :name, :street, :city)
    end
end

app/helpers/atm_machines_helper.rb
module AtmMachinesHelper
end

app/views/atm_machines/_form.html.erb
<%= form_for(@atm_machine) do |f| %>
  <% if @atm_machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atm_machine.errors.count, "error") %> prohibited this atm_machine from being saved:</h2>

      <ul>
      <% @atm_machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atm_machines/edit.html.erb
<h1>Editing Atm Machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @atm_machine %> |
<%= link_to 'Back', atm_machines_path %>

app/views/atm_machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Atm Machines</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atm_machines.each do |atm_machine| %>
      <tr>
        <td><%= atm_machine.address %></td>
        <td><%= atm_machine.latitude %></td>
        <td><%= atm_machine.longitude %></td>
        <td><%= atm_machine.name %></td>
        <td><%= atm_machine.street %></td>
        <td><%= atm_machine.city %></td>
        <td><%= link_to 'Show', atm_machine %></td>
        <td><%= link_to 'Edit', edit_atm_machine_path(atm_machine) %></td>
        <td><%= link_to 'Destroy', atm_machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Atm machine', new_atm_machine_path %>

app/views/atm_machines/new.html.erb
<h1>New Atm Machine</h1>

<%= render 'form' %>

<%= link_to 'Back', atm_machines_path %>

app/views/atm_machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @atm_machine.address %>
</p>


<p>
  <strong>Name:</strong>
  <%= @atm_machine.name %>
</p>


<p>
  <strong>City:</strong>
  <%= @atm_machine.city %>
</p>
<%=link_to 'Withdrawal'  %> &nbsp; 
<%=link_to  'Add Deposit' %> &nbsp; 
<%= link_to' Update info' %> &nbsp;
<%=link_to ' transactions'%><br>

<%= image_tag"https://maps.googleapis.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@atm_machine.latitude}%2C#{@atm_machine.longitude}" %>
<h3>Nearby ATM_Location</h3>
<ul>
<% for atm_machine in  @atm_machine.nearbys(10) %>
<li><%= link_to atm_machine.address, atm_machine %> (<%= atm_machine.distance.round(2) %> miles)</li>
<% end %>

<%= link_to 'Edit', edit_atm_machine_path(@atm_machine) %> |
<%= link_to 'Back', atm_machines_path %>